ALTER TABLE task
ADD COLUMN IF NOT EXISTS synthesized BOOLEAN NOT NULL DEFAULT FALSE;


DROP TRIGGER IF EXISTS befupd_task
ON task;

CREATE TRIGGER befupd_task
BEFORE UPDATE
ON task
FOR EACH ROW
EXECUTE PROCEDURE befupd_task();
