CREATE TABLE IF NOT EXISTS task
(
	id SERIAL PRIMARY KEY,
	name TEXT UNIQUE NOT NULL,
	state_id INTEGER NOT NULL REFERENCES task_state,
	priority INTEGER NOT NULL,
	time_limit INTERVAL NOT NULL,
	mem_limit_mb INTEGER NOT NULL
);


DROP TRIGGER IF EXISTS aftins_task
ON task;

CREATE CONSTRAINT TRIGGER aftins_task
AFTER INSERT
ON task
INITIALLY DEFERRED
FOR EACH ROW
EXECUTE PROCEDURE aftins_task();
