CREATE TABLE IF NOT EXISTS task_note_history
(
	id SERIAL PRIMARY KEY,
	task_id INTEGER NOT NULL REFERENCES task,
	note_id INTEGER NOT NULL REFERENCES task_note,
	note_args TEXT[] NOT NULL,
	time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
